//
//  AxonStore.swift
//  nervousnet-iOS
//  
//  Created by __DEVNAME__ on 03 Mar 2016.
//  Copyright (c) 2016 ETHZ . All rights reserved.
//
//WARNING - THIS CODE IS AUTOGENERATED BY DEVSKETCH AND CAN BE OVERWRITTEN


import Foundation

///
/// Axon Store gets Axon information from the local disk.
///
class AxonStore : NSObject {


func getAxons() {

}

func getAxon() {

    
}

private func getRemoteAxons() {

}

}

