//
//  AxonView.swift
//  nervousnet-iOS
//  
//  Created by __DEVNAME__ on 03 Mar 2016.
//  Copyright (c) 2016 ETHZ . All rights reserved.
//
//WARNING - THIS CODE IS AUTOGENERATED BY DEVSKETCH AND CAN BE OVERWRITTEN


import UIKit

class AxonView : UIWebView {

    /*
var baseURL:String
var URLSuffix:String
var axonName:String

func init(axonname:AnyObject) {

}
*/

}

