//
//  InstallableAxonsTableViewController.swift
//  nervousnet-iOS
//  
//  Created by __DEVNAME__ on 03 Mar 2016.
//  Copyright (c) 2016 ETHZ . All rights reserved.
//
//WARNING - THIS CODE IS AUTOGENERATED BY DEVSKETCH AND CAN BE OVERWRITTEN


import UIKit

///
/// Display a list of remotely available Axons, that can be downloaded
/// and installed.
///
public class InstallableAxonsTableViewController : UITableViewController {


func handleAxonDownloadRequest() {

}

}

