//
//  InstalledAxonsTableViewController.swift
//  nervousnet-iOS
//  
//  Created by __DEVNAME__ on 03 Mar 2016.
//  Copyright (c) 2016 ETHZ . All rights reserved.
//
//WARNING - THIS CODE IS AUTOGENERATED BY DEVSKETCH AND CAN BE OVERWRITTEN


import UIKit

///
/// Displays list of locally installed Axons.
///
internal class InstalledAxonsTableViewController : UITableViewController {


func runAxon() {

}

}

