//
//  AuthController.swift
//  nervousnet-iOS
//
//  Created by __DEVNAME__ on 04 Mar 2016.
//  Copyright (c) 2016 ETHZ . All rights reserved.
//
//WARNING - THIS CODE IS AUTOGENERATED BY DEVSKETCH AND CAN BE OVERWRITTEN


import Foundation

class AuthController : NSObject {
    
    
    func checkAppPermissions() {
        
    }
    
    ///
    /// Can be called by the UI settings.
    ///
    func changeAppPermissions() {
        
    }
    
}

