//
//  AxonController.swift
//  nervousnet-iOS
//  
//  Created by __DEVNAME__ on 03 Mar 2016.
//  Copyright (c) 2016 ETHZ . All rights reserved.
//
//WARNING - THIS CODE IS AUTOGENERATED BY DEVSKETCH AND CAN BE OVERWRITTEN


import Foundation

///
/// Manages the Axon (HTTP) server and its routes. Asks for permission on
/// behalf of the Axons.
///
class AxonController : NSObject {

override init() {

}

}

