//
//  BatteryController.swift
//  nervousnet-iOS
//  
//  Created by __DEVNAME__ on 03 Mar 2016.
//  Copyright (c) 2016 ETHZ . All rights reserved.
//
//WARNING - THIS CODE IS AUTOGENERATED BY DEVSKETCH AND CAN BE OVERWRITTEN


import Foundation

private let _BAT = BatteryController()
class BatteryController : NSObject {
    
    private var auth: Int = 0
    
    private let VM = VMController.sharedInstance
    
    var timestamp: UInt64 = 0
    var percent: Float = 0.0
    var isCharging: Bool = false
    var charging_type: Int = 0 // 0 - unknown, 1 - USB, 2 - Ac, 3 - Wireless
    
    override init() {
        
    }
    
    class var sharedInstance: BatteryController {
        return _BAT
    }
    
    func requestAuthorization() {
        
    }
    
    func initializeUpdate() {
        
    }
    
    func startSensorUpdates() {
        
    }
    
    func stopSensorUpdates() {
        
    }

 
}

