//
//  ProximityController.swift
//  nervousnet-iOS
//  
//  Created by __DEVNAME__ on 03 Mar 2016.
//  Copyright (c) 2016 ETHZ . All rights reserved.
//
//WARNING - THIS CODE IS AUTOGENERATED BY DEVSKETCH AND CAN BE OVERWRITTEN


import Foundation

class ProximityController : NSObject {
    
    private var auth: Int = 0
    
    private let VM = VMController.sharedInstance
    
    var timestamp: UInt64 = 0
    var proximity: Float = 0.0
    
    override init() {
        
    }
    
    func requestAuthorization() {
        
    }
    
    func initializeUpdate() {
        
    }
    
    func startSensorUpdates() {
        
    }
    
    func stopSensorUpdates() {
        
    }


}

