//
//  VMController.swift
//  nervousnet-iOS
//  
//  Created by __DEVNAME__ on 03 Mar 2016.
//  Copyright (c) 2016 ETHZ . All rights reserved.
//
//WARNING - THIS CODE IS AUTOGENERATED BY DEVSKETCH AND CAN BE OVERWRITTEN


import Foundation
import CoreMotion

///
/// Tells other things when to write wherever. Stores state of the privacy, permissions, frequency in NSUserDefaults.
///

private let _VM = VMController()

class VMController : NSObject {

    let motionManager: CMMotionManager
    /*
var hasEnabledAccelerometerLocalLogging:AnyObject
var accelerometerCollectionFrequency:AnyObject
var hasEnabledAccelerometerRemoteLogging:AnyObject
*/
    override init(){
        //super.init()
        self.motionManager = CMMotionManager()
    }
    
    class var sharedInstance: VMController {
        return _VM
    }
         
    func initialiseSettings() {
 
    }

    func updateSettings() {

    }

    func initialiseSensors() {

    }

}

